### ISSUE TITLE
Сделать из train.py полноценный скрипт для вызова из командной строки

### ISSUE THREAD

**Issue by PetrovitchSharp** [PetrovitchSharp/DL_CarPlates_23#1]
Добавить интерфейс для командной строки. В идеале подаем на вход путь к директории, в которой лежит трейн и разметка, а также путь для сохранения модельки, а дальше моделька сама учится и сохраняется.

**Comment by mikgur** [comment]
Done.

[commit](https://github.com/PetrovitchSharp/DL_CarPlates_23/commit/737763c3fc07e42dcd974b539c471fec60d93377)
