### ISSUE TITLE
Сделать из inference.py полноценный скрипт для вызова из командной строки

### ISSUE THREAD

**Issue by PetrovitchSharp** [PetrovitchSharp/DL_CarPlates_23#2]
По аналогии с #1 добавить интерфейс для командной строки. В идеале подаем на вход путь к картинке, путь к модельке и путь для сохранения картинки. Далее происходит инференс и все такое

**Comment by mikgur** [comment]
Done.

[commit](https://github.com/PetrovitchSharp/DL_CarPlates_23/commit/2acc589847d3b4f17e63d7a8f0c60f7b057e97cf)
