### ISSUE TITLE
Добавить requirements

### ISSUE THREAD

**Issue by PetrovitchSharp** [PetrovitchSharp/DL_CarPlates_23#6]
Добавить requirements.txt

**Comment by mikgur** [comment]
Добавил poetry: pyproject.toml, poetry.lock

Единственное - нужно проверять версию torch, torchvision в pyproject.toml (например у меня cuda 11.6). Если версия не совпадает - то меня руками в pyproject.toml и удалять poetry.lock, тогда poetry install пересоберет полностью окружение.

[commit](https://github.com/PetrovitchSharp/DL_CarPlates_23/commit/059e2c63f587253122d95260d377cee973ba18c9)
